### ISSUE TITLE
Jon still hasn't posted his detailed proposal about shooter control

### ISSUE THREAD

**Issue by em-ly** [jonstokes/shootercontrol#3]
and I'm super interested in reading it, so, creating this issue to stir up some peer pressure for more positive discussion.

**Comment by beefyjuggurnaut** [comment]
I am too, when do you think it will go up?

**Comment by ghost** [comment]
I am also interested.

Regards,

Dave Reese
408-813-5058

**Comment by hsoi** [comment]
Folks - if you're interested in this and wish to follow developments, then go click on the "Watch" button in the upper-right corner of the screen.

There's no need to keep posting as such to this Issue.

**Comment by em-ly** [comment]
@hsoi perhaps you're unfamiliar with the social tool of peer pressure. :) Watching the issue would notify us, but I'm making sure that @jonstokes knows that the demand is here.

**Comment by RussNelson** [comment]
Uh, he knows, and you're sending this email out to everyone. Patience ... patience.

**Comment by jonstokes** [comment]
Hey guys, I'm kind of overwhelmed with the response to the original article, and have circulated some parts of it in private to get some feedback. I'll try to get it up ASAP.

It's really rough and is a work in progress. I don't want to oversell it. What it actually is (hopefully) is a conversation starter.

**Comment by jonstokes** [comment]
Ok, please see the pull requests queue. I've now put something up. Again, I don't claim to have all the answers, and I expect everyone to hate this :p
